### ISSUE TITLE
合并转发base64超时无法发出

### ISSUE THREAD

**Issue by CCYellowStar2** [Hoshinonyaruko/Gensokyo#121]
![WH3}2FG DI(D2VR30 VS%@G](https://github.com/Hoshinonyaruko/Gensokyo/assets/149048350/df8bc142-9101-4c66-b4cb-99d830adae55)
已经测试不使用合并转发可以发出来

**Comment by zhzhongshi** [comment]
日志里好像还写入了图片的base64，这可能会造成日志文件非常巨大（

**Comment by SanaeFox** [comment]
现已修复
