### ISSUE TITLE
在webui提交配置会断开连接结束程序

### ISSUE THREAD

**Issue by zhzhongshi** [Hoshinonyaruko/Gensokyo#131]
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/39423408/b472942d-f127-420c-a69c-dce8f7df4c8b)
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/39423408/3f09eaf8-a2fc-4ea5-8980-520734557aa4)
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/39423408/46600392-ed8c-453a-af26-190a9677bee1)
应用好像结束了（

**Comment by zhzhongshi** [comment]
ubuntu 20.04(

**Comment by zhzhongshi** [comment]
我发现在目录下会生成脚本restart.sh
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/39423408/36622603-1eda-47d1-b228-4464688ffde7)
但是路径并不对

**Comment by Hoshinonyaruko** [comment]
感谢liyk123提交的修复~
