### ISSUE TITLE
获取子频道api返回错误

### ISSUE THREAD

**Issue by yuanban** [Hoshinonyaruko/Gensokyo#140]
获取子频道api返回错误
![屏幕截图 2023-11-19 124548](https://github.com/Hoshinonyaruko/Gensokyo/assets/44919787/e563c2a6-098c-4927-a68e-ec5f5acc710b)

**Comment by dlcnx** [comment]
action部分，请求参数里的频道ID(guild_id)为0是对的吗？不知道这个id从哪得到的。
至于error，是你的go-cqhttp插件没有处理返回数据为空的情况。

**Comment by dlcnx** [comment]
看了下，get_guild_list接口返回的guild_id很可能有问题

**Comment by Hoshinonyaruko** [comment]
更新,你落后了120个版本
