### ISSUE TITLE
频道发送一个指令机器人响应两次

### ISSUE THREAD

**Issue by Xingheee** [Hoshinonyaruko/Gensokyo#155]
<img width="461" alt="image" src="https://github.com/Hoshinonyaruko/Gensokyo/assets/126763396/2fb9797a-ebab-43b6-b410-e559e980d5cd">
只要@了机器人就响应两次，直接发送正常，已排除后端插件问题

**Comment by liyk123** [comment]
我也遇到了这个问题

**Comment by 2022717137** [comment]
在配置文件的intent，第一个At信息 和私域的非at intent事件，只需要选择一个
