### ISSUE TITLE
希望将群聊中的空指令也交由用户后台处理

### ISSUE THREAD

**Issue by myzuhang1234** [Hoshinonyaruko/Gensokyo#164]
版本：v163
环境：QQ群

![J76J6PM3S21B`R_J3 )JSN0](https://github.com/Hoshinonyaruko/Gensokyo/assets/71259897/27df74c7-32c8-495e-89ab-06fb45ce5543)

问题1：手机端只@机器人不接指令 后台接受不到消息 gsk日志

 	[Intent:1107300352] receive Event message, {"op":0,"s":3,"t":"GROUP_AT_MESSA
 	GE_CREATE","id":"GROUP_AT_MESSAGE_CREATE:95l4tdlib8mtvkwxdexoanzadtrvswkvnztu
 	qcdgzsncy77s33ypdf8gdt","d":{"author":{"id":"9A2327F233DF4AA6411D87F07683A6B","
 	member_openid":"9A2327F233DF4AA6411D87F07683A6B"},"content":" ","group_id":"CD4
 	8C0B43B966A9333DE3AA457563BE9","group_openid":"CD48C0B43B966A9333DE3AA457563BE9"
 	,"id":"ROBOT1.0_95L4T.DLIB8mtVKwxdeXOXmG7XB2RnwtraQCVO5Mr-VAnICLHds.ykkOfPYyYBwc
 	","timestamp":"2023-11-22T21:37:45+08:00"}}
 	2023/11/22 21:37:46 信息被自定义黑白名单拦截

问题2：电脑端@机器人不接指令 后台和gsk均无消息（如果是官方限制请忽略）

 gsk配置文件

 	white_prefix_mode : false         
 	white_prefixs : [""]              

 	black_prefix_mode : false        
 	black_prefixs : [""]             

 	visual_prefixs : [""]           

手机和电脑在频道中只@不接指令 均会正确将空消息传给用户后台 接收的消息为 "content":""

ps:我的后台功能分正式版和审核版，群聊中输入一段神秘代码可将审核版转正式版。所以在不同群聊中空指令的回复也会不一样，希望将空指令传给用户后台处理。

**Comment by Hoshinonyaruko** [comment]
已修复,更新最新版gsk
