### ISSUE TITLE
重启之后有几率会报错403

### ISSUE THREAD

**Issue by hui-ld** [Hoshinonyaruko/Gensokyo#173]
gsk不重启，nb2重启发送第一条命令时有几率触发，版本是最新版本
但是。。。消息正常响应，就报错403

gensokyo端报错

2023/11/25 18:53:42 Failed to connect to WebSocket[ws://127.0.0.1:25550/onebot/v11/ws/]: websocket: bad handshake, retrying in 5 seconds...
2023/11/25 18:53:47 Dialing URL: ws://127.0.0.1:25550/onebot/v11/ws/
2023/11/25 18:53:47 Failed to connect to WebSocket[ws://127.0.0.1:25550/onebot/v11/ws/]: websocket: bad handshake, retrying in 5 seconds...
2023/11/25 18:53:51 DEBUG: [ws][ID:41d2c44e-d562-46c5-89a1-0bfaa1ec1bdd][Shard:(0/1)][Intent:1107300864] listened heartBeat
2023/11/25 18:53:51 INFO: [ws][ID:41d2c44e-d562-46c5-89a1-0bfaa1ec1bdd][Shard:(0/1)][Intent:1107300864] write Heartbeat message, {"op":1,"d":0}
2023/11/25 18:53:51 INFO: [ws][ID:41d2c44e-d562-46c5-89a1-0bfaa1ec1bdd][Shard:(0/1)][Intent:1107300864] receive HeartbeatAck message, {"op":11}
2023/11/25 18:53:52 Dialing URL: ws://127.0.0.1:25550/onebot/v11/ws/
2023/11/25 18:53:52 Failed to connect to WebSocket[ws://127.0.0.1:25550/onebot/v11/ws/]: websocket: bad handshake, retrying in 5 seconds...

nonebot2端报错

11-25 18:50:47 [INFO] uvicorn \| Application startup complete.
--
11-25 18:50:47 [INFO] uvicorn \| Uvicorn running on http://0.0.0.0:25550 (Press CTRL+C to quit)
11-25 18:50:49 [INFO] uvicorn \| ('127.0.0.1', 44428) - "WebSocket /onebot/v11/ws/" [accepted]
11-25 18:50:49 [INFO] nonebot \| OneBot V11 \| Bot 10207xxxx connected
11-25 18:50:49 [INFO] websockets \| connection open
11-25 18:53:07 [SUCCESS] nonebot \| OneBot V11 102075551 \| [message.group.normal]: Message 223 from 41518xxxx@[群:1] '今天吃什么'
11-25 18:53:07 [WARNING] nonebot \| OneBot V11 \| There's already a bot 102075551, ignored
11-25 18:53:07 [INFO] uvicorn \| ('127.0.0.1', 52944) - "WebSocket /onebot/v11/ws/" 403
11-25 18:53:07 [INFO] websockets \| connection rejected (403 Forbidden)
11-25 18:53:07 [INFO] websockets \| connection closed
11-25 18:53:07 [INFO] nonebot \| Event will be handled by Matcher(type='message', module=nonebot_plugin_whateat_pic, lineno=69)
11-25 18:53:08 [INFO] nonebot \| Matcher(type='message', module=nonebot_plugin_whateat_pic, lineno=69) running complete
11-25 18:53:12 [WARNING] nonebot \| OneBot V11 \| There's already a bot 102075551, ignored
11-25 18:53:12 [INFO] uvicorn \| ('127.0.0.1', 55292) - "WebSocket /onebot/v11/ws/" 403
11-25 18:53:12 [INFO] websockets \| connection rejected (403 Forbidden)
11-25 18:53:12 [INFO] websockets \| connection closed

**Comment by CCYellowStar2** [comment]
+1

**Comment by 2022717137** [comment]
更新最新版gsk
