### ISSUE TITLE
框架会删除所有链接，包括后台添加并且验证过的链接

### ISSUE THREAD

**Issue by watagashi-uni** [Hoshinonyaruko/Gensokyo#209]
### 实际的结果：

发送的消息带链接时，框架会一律删除链接部分，包括在管理后台 **开发设置** - **消息URL配置** 中添加并验证过的链接，该功能无开关。

### 期望的结果：

用户可在配置文件中自行开关链接删除功能。

**Comment by Hoshinonyaruko** [comment]
已更新,
但反驳你的描述,
框架不是删除链接部分,而是未正确配置server dir crt和key时会删除,
已允许自定义该状态
 transfer_url : true                #默认开启,关闭后自理url发送,配置server_dir为你的域名,配置crt和key后,将域名/url和/image在q.qq.com后台通过校验,自动使用302跳转处理机器人发出的所有域名.
但您的issue涉及不正确的描述,会造成误解.

**Comment by watagashi-uni** [comment]
已修改描述 感谢更新
