### ISSUE TITLE
使用overflow套用gsk在频道发送图片消息失败

### ISSUE THREAD

**Issue by BoYuanCN** [Hoshinonyaruko/Gensokyo#242]
## 环境信息

- 操作系统：win10,
- OneBot SDK：Overflow 2.16
- gsk版本：Release 241/merge

## 问题描述

使用overflow调用mirial发送图片消息，QQ群能正常发送成功，频道发送失败。文字消息的话不论在Q群还是频道均能正常发送成功

## 期望行为

与Q群一样发送图片成功。

## 其他信息

overflow代码：   
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/40412198/beb9c45a-b81f-4685-9386-a6a1b8557a4f)

发送图片频道失败与Q群成功报文：
![image](https://github.com/Hoshinonyaruko/Gensokyo/assets/40412198/4d064edc-cd81-4330-a0fe-21791961e1a0)

**Comment by Hoshinonyaruko** [comment]
频道不支持oss地址,与gsk无关.请等待官方支持,将报错提交到qq官方报错表.
