### ISSUE TITLE
希望增加gocq一样的统计api

### ISSUE THREAD

**Issue by 2598142880** [Hoshinonyaruko/Gensokyo#249]
在状态插件中，收消息次数固定为500，发消息次数固定为400，希望gsk可以适配.
状态插件
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus
能增加统计群数量的更好（
gocq状态api
https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%8A%B6%E6%80%81
字段 | 类型 | 说明
-- | -- | --
packet_received | uint64 | 收到的数据包总数
packet_sent | uint64 | 发送的数据包总数
packet_lost | uint32 | 数据包丢失总数
message_received | uint64 | 接受信息总数
message_sent | uint64 | 发送信息总数
disconnect_times | uint32 | TCP 链接断开次数
lost_times | uint32 | 账号掉线次数
last_message_time | int64 | 最后一条消息时间

**Comment by 2022717137** [comment]
已经实现
