### ISSUE TITLE
配置文件中反向ws填写两个，但只启用连接上一个，gsk会报错或bot收不到消息

### ISSUE THREAD

**Issue by 2598142880** [Hoshinonyaruko/Gensokyo#271]
配置文件中反向ws填写两个，但只启用连接上一个，gsk会报错或bot收不到消息。
单独启用yunzai，启动gsk会崩溃。
单独启用nb，启动gsk，nb收不到消息，但gsk可以。
若在配置文件中只保留一个ws，则可以正常使用

**Comment by 2598142880** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x190 pc=0x84d70d]

goroutine 47 [running]:
github.com/boltdb/bolt.(*DB).beginTx(0x0)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:470 +0x2d
github.com/boltdb/bolt.(*DB).Begin(0xc?, 0x5?)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:463 +0x25
github.com/boltdb/bolt.(*DB).View(0x1b2e5c8?, 0xc0003c1908)
        /home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:613 +0x30
github.com/hoshinonyaruko/gensokyo/idmap.FindKeysBySubAndType({0xa10af3?, 0x9?}, {0xa0fb55?, 0xc0004b02e8?})
        /home/runner/work/Gensokyo/Gensokyo/idmap/service.go:1092 +0x78
github.com/hoshinonyaruko/gensokyo/handlers.GetGroupList({_, _}, {_, _}, {_, _}, {{0xc000131d50, 0xe}, {{0x0, 0x0}, ...}, ...})
        /home/runner/work/Gensokyo/Gensokyo/handlers/get_group_list.go:131 +0x699
github.com/hoshinonyaruko/gensokyo/callapi.CallAPIFromDict({_, _}, {_, _}, {_, _}, {{0xc000131d50, 0xe}, {{0x0, 0x0}, ...}, ...})
        /home/runner/work/Gensokyo/Gensokyo/callapi/callapi.go:180 +0xed
github.com/hoshinonyaruko/gensokyo/wsclient.(*WebSocketClient).recvMessage(0xc00066b020, {0xc0005bba00, 0x49, 0x200})
        /home/runner/work/Gensokyo/Gensokyo/wsclient/ws.go:135 +0x22b
created by github.com/hoshinonyaruko/gensokyo/wsclient.(*WebSocketClient).handleIncomingMessages in goroutine 49
        /home/runner/work/Gensokyo/Gensokyo/wsclient/ws.go:71 +0x27

**Comment by LsrlYrsc** [comment]
[issue:270](https://github.com/Hoshinonyaruko/Gensokyo/issues/270)

**Comment by 2598142880** [comment]
新发现：在gsk成功连接后，关闭nb再开启nb可以收到消息，但是yunzai关闭再开启不可以

**Comment by Hoshinonyaruko** [comment]
填写多个ws时需要保证多个ws均可用

**Comment by Hoshinonyaruko** [comment]
修好咯!
