### ISSUE TITLE
能否添加不载入本地token的配置？我这有个bot貌似只能用access_token

### ISSUE THREAD

**Issue by AmicBeam** [Hoshinonyaruko/Gensokyo#292]
![fce7717b3084de6fed1d8a2a5ba2d58a](https://github.com/Hoshinonyaruko/Gensokyo/assets/43090179/04dadb18-ef39-4649-a399-01455905fd5f)

启动时能看到第一行的获取到的token是：%s
Aq.........r7

**Comment by Hoshinonyaruko** [comment]
access token 3600s过期,机器人token不可分享
