### ISSUE TITLE
请实现和gocq一致的get status接口

### ISSUE THREAD

**Issue by SanaeFox** [Hoshinonyaruko/Gensokyo#299]
参考https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%8A%B6%E6%80%81
忽略packet_received	uint64	收到的数据包总数
packet_sent	uint64	发送的数据包总数
packet_lost	uint32	数据包丢失总数
gsk现有代码中，已包含返回数据的格式，完善统计设计
希望延用采用bolt数据库的形式，新增一个独立的db数据库，用于储存
并填入即可。

**Comment by 2022717137** [comment]
已实现！
