### ISSUE TITLE
QQ群艾特事件无效

### ISSUE THREAD

**Issue by timibox** [Hoshinonyaruko/Gensokyo#309]
本人已经申请的企业QQ机器人 有Q群的能力
测试发现 机器人加群跟退群的事件 有效
但是群内艾特机器人发送命令 没任何事件响应

使用官方API 主动往群里发信息也测试正常
并且在WEBUI端 点获取群聊也没任何群信息

`2024/1/17 12:48:29INFOINFO: [ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive Event message, {"op":0,"s":2,"t":"GROUP_MSG_REJECT","id":"GROUP_MSG_REJECT:576a5d16-e4e8-4a10-81e4-f2688a959215","d":{"group_openid":"2523D6C1668EF591D05A763B73B48030","op_member_openid":"332B5D7F5684326D68E56C14142B68E7","timestamp":1705466908}}
2024/1/17 12:48:29INFO[ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive Event message, {"op":0,"s":2,"t":"GROUP_MSG_REJECT","id":"GROUP_MSG_REJECT:576a5d16-e4e8-4a10-81e4-f2688a959215","d":{"group_openid":"2523D6C1668EF591D05A763B73B48030","op_member_openid":"332B5D7F5684326D68E56C14142B68E7","timestamp":1705466908}}
2024/1/17 12:48:33INFOINFO: [ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive Event message, {"op":0,"s":3,"t":"GROUP_MSG_RECEIVE","id":"GROUP_MSG_RECEIVE:ebec0cf8-a201-476c-b464-48013cedf6d3","d":{"group_openid":"2523D6C1668EF591D05A763B73B48030","op_member_openid":"332B5D7F5684326D68E56C14142B68E7","timestamp":1705466912}}
2024/1/17 12:48:33INFO[ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive Event message, {"op":0,"s":3,"t":"GROUP_MSG_RECEIVE","id":"GROUP_MSG_RECEIVE:ebec0cf8-a201-476c-b464-48013cedf6d3","d":{"group_openid":"2523D6C1668EF591D05A763B73B48030","op_member_openid":"332B5D7F5684326D68E56C14142B68E7","timestamp":1705466912}}
2024/1/17 12:48:40INFO[ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] write Heartbeat message, {"op":1,"d":0}
2024/1/17 12:48:40INFOINFO: [ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] write Heartbeat message, {"op":1,"d":0}
2024/1/17 12:48:40INFO[ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive HeartbeatAck message, {"op":11}
2024/1/17 12:48:40INFOINFO: [ws][ID:8ec65117-fecf-4d67-82f8-f2ade8f35b00][Shard:(0/1)][Intent:1107300352] receive HeartbeatAck message, {"op":11}`

**Comment by Hoshinonyaruko** [comment]
请参考教程,正确设置intent
https://www.yuque.com/km57bt/hlhnxg/hoxlh53gg11h7r3l

**Comment by Hoshinonyaruko** [comment]
GROUP_MSG_REJECT,检查Q群是否设置拒绝机器人发送信息.
