### ISSUE TITLE
真寻的图文信息混合，读取不到文件夹图片

### ISSUE THREAD

**Issue by nuanyang0929** [Hoshinonyaruko/Gensokyo#312]
2024/01/23 09:32:10 RawMessage: 签到
2024/01/23 09:32:10 MessageID: 4
2024/01/23 09:32:10 GroupID: 1
2024/01/23 09:32:10 MessageType: group
2024/01/23 09:32:10 PostType: message
2024/01/23 09:32:10 SelfID: 102078348
2024/01/23 09:32:10 Sender: {  2 owner  0 0 0 0 }
2024/01/23 09:32:10 SubType: normal
2024/01/23 09:32:10 Time: 1705973530
2024/01/23 09:32:10 Avatar:
2024/01/23 09:32:10 Echo:
2024/01/23 09:32:10 Message: 签到
2024/01/23 09:32:10 MessageSeq: 0
2024/01/23 09:32:10 Font: 0
2024/01/23 09:32:10 UserID: 2
2024/01/23 09:32:10 RealMessageType: group
2024/01/23 09:32:10 IsBindedGroupId: false
2024/01/23 09:32:10 IsBindedUserId: false
2024/01/23 09:32:12 Received from onebotv11 server: Action: send_msg, Params: {"botqq":"","channel_id":"","guild_id":"","group_id":"1","message":[{"data":{"qq":"2"},"type":"at"},{"data":{"text":" "},"type":"text"},{"data":{"cache":"true","file":"file:///C:/Users/Administrator/Desktop/ZX%20least/resources/image/sign/today_card/2_1_sign_2024-01-23.png","proxy":"true","timeout":null,"type":null},"type":"image"}],"user_id":"2","context":{},"operation":{}}, Echo: 23676
2024/01/23 09:32:12 send_group_msg获取到信息类型:group
2024/01/23 09:32:12 params.message is a slice (segment_type_koishi)
2024/01/23 09:32:12 echo取群组发信息对应的message_id:
2024/01/23 09:32:12 群组发信息messageText:
2024/01/23 09:32:12 GetMessageIDByUseridAndGroupid_key:102078348_1_2
2024/01/23 09:32:12 通过GetMessageIDByUseridAndGroupid函数获取的message_id: D2932818653EEB4D146011C19B6860F4 ROBOT1.0_hUsbU4BDurQindfdoB.Jhzqfc65k8x2Pngk8JdZXsL2a85l6z7HVw0uM8EB7o6Ooy0bzWi8-PDzwfCMemkroZw!!
2024/01/23 09:32:12 群组发信息使用messageID:[ROBOT1.0_hUsbU4BDurQindfdoB.Jhzqfc65k8x2Pngk8JdZXsL2a85l6z7HVw0uM8EB7o6Ooy0bzWi8-PDzwfCMemkroZw!!]
2024/01/23 09:32:12 发图文混合信息-群
2024/01/23 09:32:12 Error reading the image from path C:/Users/Administrator/Desktop/ZX%20least/resources/image/sign/today_card/2_1_sign_2024-01-23.png: open C:/Users/Administrator/Desktop/ZX%20least/resources/image/sign/today_card/2_1_sign_2024-01-23.png: The system cannot find the path specified.
2024/01/23 09:32:12 Error: Expected RichMediaMessage type for key

大佬帮忙看看是哪里的问题

**Comment by Hoshinonyaruko** [comment]
文件夹名不要用空格
