### ISSUE TITLE
对config的请教

### ISSUE THREAD

**Issue by ANGJustinl** [Hoshinonyaruko/Gensokyo#322]
# 如题,公域机器人已经可以正常收发消息,比较好奇
>server_dir:                  # 提供图片上传服务的服务器(图床)需要带端口号. 如果需要发base64图,需为公网ip,且开放对应端口
>port:                                       # idmaps和图床对外开放的端口号
>backup_port :                               # 当totus为ture时,port值不再是本地webui的端口,使用lotus_Port来访问webui
>oss_type:
>穿透\cos\oss类配置(可选!)
>frp_port : "0"                    #不使用请保持为0,frp的端口,frp有内外端口,请在frp软件设置gensokyo的port,并将frp显示的对外端口填入这里
>#腾讯云配置
>...配置

这些我没找到相关文档所以我不太明白 :(

# 还有图文混合消息发送失败有没有办法向bot段发送一个回调?我这边失败也算bot完成了handler(nonebot)

**Comment by ANGJustinl** [comment]
我比较愚笨没太看懂注释XD

**Comment by Hoshinonyaruko** [comment]
https://www.yuque.com/km57bt/hlhnxg/cr4ongt8qr7yqvdq

**Comment by ANGJustinl** [comment]
这篇文档我看了,但里面没提到 `穿透\cos\oss类配置(可选!)`
