### ISSUE TITLE
在设置image_sizelimit的情况下，发送频道和私聊的图片不会压缩

### ISSUE THREAD

**Issue by Yulinlinnya** [Hoshinonyaruko/Gensokyo#330]
在设置image_sizelimit的情况下，发送频道和私聊的图片不会压缩。
![设置](https://github.com/Hoshinonyaruko/Gensokyo/assets/153787143/1c54ddcd-5f04-4bd1-a60c-191debdfac39)
![日志](https://github.com/Hoshinonyaruko/Gensokyo/assets/153787143/d3056a02-0927-412c-9f5b-39347e0e32de)
这是我更换背景图后，发出图片的大小。群聊是正常压缩的。
![总评](https://github.com/Hoshinonyaruko/Gensokyo/assets/153787143/8b63b95c-66de-4800-a5eb-076319760139)

**Comment by Yulinlinnya** [comment]
补充：Release 329/merge

**Comment by 2022717137** [comment]
已修复了https://github.com/Hoshinonyaruko/Gensokyo/releases/tag/331%2Fmerge
