### ISSUE TITLE
入群主动发送失败的问题

### ISSUE THREAD

**Issue by Gordenqiu** [Hoshinonyaruko/Gensokyo#334]
一个新群没@过机器人触发指令的就发不了入群主动，@机器人触发过指令后，t掉重新拉就能发入群主动，复现率100%
日志：
全新的群拉入：
![10f564c2b850a291ec55a3672425beb2](https://github.com/Hoshinonyaruko/Gensokyo/assets/87472651/30ba9a10-1855-4b3e-aa81-36bc04c8061d)
触发过一次指令后拉入：
![b24a2824d55e89f692e06749ee50d37d](https://github.com/Hoshinonyaruko/Gensokyo/assets/87472651/c8628c52-3a87-4855-a8a0-a10af5f2ef5f)

推测原因:首次入群时，4种方法都不能判断msgtype，导致日志msgtype记录为空，并进入递归
![c659a8d1da846a14e1cc11461daa4ce3](https://github.com/Hoshinonyaruko/Gensokyo/assets/87472651/0ca28661-481d-494f-875f-807a72926fd8)

**Comment by Gordenqiu** [comment]
并且该消息也不会随着下一次被动被带出

**Comment by SanaeFox** [comment]
你进群时候
你有一个应用端行为
这个应用端发来的action
影响了框架的递归
你要去掉它
去掉这个action
让框架自己发，不然就会有2个递归同时进行，然后冲突。

**Comment by SanaeFox** [comment]
还有你的日志只截图了一半，以后要提供完整的日志

**Comment by Hoshinonyaruko** [comment]
错误原因是群聊函数递归，私聊函数也有递归，因为我和wrds能运行的原因，都是我们在私聊函数进入重复递归之前，就报错返回了，我是因为lotus报错返回，wrds上传报错返回，这2个报错让我们侥幸可以正常运行。
但是茶报错的地方，没有返回（遗漏了），于是群聊的递归就进入了私聊，在私聊递归了3次，发了4次私聊，没有递归到群这里。
然后我就在应该返回的地方加了个返回，问题就修好了。
