### ISSUE TITLE
希望完善这些地方

### ISSUE THREAD

**Issue by SanaeFox** [Hoshinonyaruko/Gensokyo#4]
- [x] 建立echo映射id和类型
- [x] 建立uuid到固定int数据库映射
- [x] 将它修改成多个gensokyo可互相连接
- [x] （同一个bot多开公用一个映射）
- [x] 频道私域信息事件
- [x] 频道文字信息
- [x] 频道链接图
- [x] 群组文字信息
- [x] 群组链接图
- [x] 使用bolt数据库替代ini
- [x] 兼容https://github.com/Ice9Coffee/HoshinoBot
- [x] 频道私聊（私聊模式）
- [x] 频道私聊（频道模式）
- [x] 频道私聊（群模式）
- [x] 群私聊（私聊模式）
- [x] 群私聊（群模式）
- [x] 群信息的array
- [x] 频道信息array
- [x] 私信array
- [x] 回复类型信息（群）
- [x] （每个地方的array信息段都要支持）
- [x] Nb2插件测试 文字 图像
- [x] Koishi插件测试 文字 图像
- [x] 早苗插件测试 文字 图像
- [x] Trss插件测试 文字 图像
- [x] 獭獭 wss信息的accesstoken 文字 图像 测试
- [x] 频道base64图
- [x] 频道本地路径图
- [x] 群组base64图
- [x] 群组本地图
- [x] 发送成功后会返回发送成功回执，要组合成onebotv11的回执
- [x] 群组base64语音
- [x] 群组本地路径语音（搁置）
- [x] 频道禁言api 
- [x] 群禁言api
- [x] 断线重连
- [x] 多个ws连接思路，多开

**Comment by Hoshinonyaruko** [comment]
搞定
