### ISSUE TITLE
无法发送gif

### ISSUE THREAD

**Issue by xszqxszq** [Hoshinonyaruko/Gensokyo#422]
使用overflow正向ws连接Gensokyo，并使用腾讯OSS上传图片，系统为Centos Stream 8

无论多大的gif，发送gif之后Gensokyo日志都会提示：
```
Error compressing image: decoding GIF image failed: gif: not enough image data
```
并且报图片压缩失败，其他非gif图片都正常。试过很多张gif都不行

**Comment by 2022717137** [comment]
图片压缩设置为0，不开启图片压缩即可解决。
